name: Update requirements.txt

on:
  push:
    paths:
      - poetry.lock

jobs:
  update-requirements:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'  # Specify the Python version you need

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.8.3

    - name: Install dependencies
      run: poetry install

    - name: Export dependencies to requirements.txt
      run: poetry export --without-hashes --without-urls | awk '{ print $1 }' FS=';' > requirements.txt

    - name: Show generated requirements.txt
      run: cat requirements.txt

    - uses: EndBug/add-and-commit@v9
      with:
        message: Export requirements.txt